name: combe
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  lavalink: ^1.0.0
  nyxx: ^6.5.0
  nyxx_lavalink: ^4.0.0-dev.1
  subsonic_api: ^0.0.6
  toml: ^0.16.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
